/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.1-13-g4991c1ec92"
#endif /* AVUTIL_FFVERSION_H */
